name: Build and deploy Python project to Azure Function App - myiotappcode

on:
  push:
    branches:
      - main
    paths:
      - "src/functions/**"
      - ".github/workflows/main_myiotappcode.yml"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/functions'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into package folder
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4AB089ED4F34D4490FA20D346968E9A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C37AB9858FC94F8C91D31986D8C429DB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_75001E64730B4EE583A34CCD597BE131 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'myiotappcode'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
